---
title: "BIO1410 - 2026 - Analyses R"
author: "Karine Villeneuve"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# Introduction

Ce petit guide à été rédigé à l'intention des élèves du cours BIO1410 afin de familiariser les étudiants au traitement de données de séquençage d'amplicons en utilisant le langage de programmation R avec l'IDE R Studio. 

1. La première section [Introduction à R et RStudio] présente brièvement R et R Studio. 

2. La seconde section [Utiliser RStudio et R Mardown] introduit quelques notions de bases en R et explique comment élaborer des scripts avec RStudio en format R ou R Markdown. 

3. La troisième section [Vos ASVs et BLAST] est un petit exercice de programmation R. 

4. La quatrième section [Traitement des fastqs] présente ensuite comment les données brutes du séquençage d'amplicon du gène ARNs 16S ont été traitées dans R afin d'obtenir une matrice d'abondance relative des variants de séquence d'amplicon (ASVs) par échantillon. 

5. La section [Statistiques] présente l'ensemble des analyses statistiques réalisées avec R afin de comparer le microbiote des deux régions échantillonnées. 

6. Finalement, la section [Installer R et RStudio ] indique les liens pour télécharger chacun des programmes. 



comprend un petit script R permettant à l'élève d'identifier les 10 genres bactériens les plus abondants dans ses échantillons récoltés sous sa langue ainsi que sur la paume de sa mains. Ce script permet aussi de générer un tableau de données en format *comma seperated value* (csv) que l'étudiant devra utiliser pour obtenir la séquence d'acides nucléiques du taxon choisi. La séquence pourra ensuite être rechercher dans la base de données du National Center for Biotechnology Information (NCBI) avec leur outil *Basic Local Alignment Search Tool* ([BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi)) afin d'obtenir une classification plus précise que le genre. 

La quatrième section [R Markdown] aborde une différentes manière de rédiger ses scripts favorisant l'annotation et l'organisation du code en plus de l'exportation des scripts sous différents formats (PDF, HTML, etc.) pour le partage des scripts.

